# config.yaml
telegram_token: ""
allowed_users:
  - 123456789
  - 987654321
download_dir: "D:/server/volumes/music/new"

spotify:
  client_id: ""
  client_secret: ""

yandex:
  username: ""
  password: ""

cookies:
  youtube: "D:/server/volumes/www.youtube.com_cookies.txt"

file_upload:
  # Where to place files that users upload directly to the bot
  subdir: "Telegram Uploads"

  # Allowed extensions Navidrome/FFmpeg commonly handle.
  # Case-insensitive; include dot.
  allowed_exts:
    - .mp3
    - .flac
    - .m4a
    - .aac
    - .ogg
    - .opus
    - .wav
    - .aiff
    - .aif
    - .wma
    - .dsf
    - .dff
    - .mka

metadata_lookup:
  enable: true
  min_confidence: 0.5        # минимальный score от AcoustID/MusicBrainz
  acoustid_api_key: ""       # получить на acoustid.org
  musicbrainz_useragent: "MusicBot/0.1 (youremail@example.com)"
  lastfm_api_key: ""
  discogs:
    user_agent: "MusicBot/0.1"
    token: ""                # Discogs personal token (опц)
  prefer_existing_tags: true # не перезаписывать заполненные поля
  fetch_cover_art: true
